_base: "./base.yaml"

log:
  comment: "city"

data:
  weak_transforms:
    batch_apply:
      normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
        - True
        - False
    batch_pad:
      fixed_size: [512, 512]
  strong_transforms:
    batch_apply:
      random_color_jitter:
        - 0.8
        - 0.5
        - 0.5
        - 0.5
        - 0.25
      random_grayscale:
      random_gaussian_blur:
      normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
        - True
        - False
      k_random_erase:
        scale: [0.02, 0.4]
        ratio: [0.3, 3.3]
        p: 0.5
    batch_pad:
      fixed_size: [512, 512]
  train_l:
    dataset: "Cityscapes"
    subset: "l.1.72.fold2"
    prefetch: False
    infinity_sampler: True
    root: "./data/cityscapes"
    num_workers: 4
    batch_size: 4
    shuffle: True
    img_transforms:
    batch_transforms:
      batch_apply:
        resize:
          scale: [0.5, 0.75, 1, 1.5, 1.75, 2.0]
        random_crop:
          - [512, 512]
        random_horizontal_flip:
  train_u:
    dataset: "Cityscapes"
    subset: "u.1.72.fold2"
    prefetch: False
    infinity_sampler: True
    root: "./data/cityscapes"
    num_workers: 4
    batch_size: 4
    shuffle: True
    img_transforms:
    batch_transforms:
      batch_apply:
        resize:
          scale: [0.5, 0.75, 1, 1.5, 1.75, 2.0]
        random_crop:
          - [512, 512]
        random_horizontal_flip:
  test:
    dataset: "Cityscapes"
    subset: "val"
    prefetch: False
    infinity_sampler: False
    root: "./data/cityscapes"
    num_workers: 1
    batch_size: 1
    shuffle: False
    img_transforms:
    batch_transforms:
      batch_apply:
        resize:
          min_size: [1024, 1024]
          max_size: 2048
          mode: "choice"
          process_label: False
        normalize:
          - [0.485, 0.456, 0.406]
          - [0.229, 0.224, 0.225]
          - True
          - False
      batch_pad:
        stride: 1

model:
  num_classes: 19

solver:
  iter_num: 80000
  burnin_iter_num: 2000
  eval_interval: 1000
  ckp_interval: 5000
  ema_momentum: 0.9996
  ema_bn: True
  u_loss_weight: 1
  optimizer:
    type: "sgd"
    lr: 0.002
    weight_decay: 0.0001
    weight_decay_norm: 0
    weight_decay_bias: 0
    momentum: 0.9
  lr_scheduler:
    type: "const"
    warmup: True
    warmup_step: 500
    warmup_gamma: 0.001
